# Generated by Django 5.1.7 on 2025-03-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0002_rename_name_product_genre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Drakor',
        ),
    ]
