# Generated by Django 5.1.7 on 2025-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0004_drama_delete_drakor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='drama',
            name='image_url',
        ),
        migrations.AddField(
            model_name='drama',
            name='genre',
            field=models.ManyToManyField(to='rekomendasi.genre'),
        ),
    ]
