# Generated by Django 5.1.7 on 2025-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0005_genre_remove_drama_image_url_drama_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drakor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('tahun', models.PositiveIntegerField()),
                ('sinopsis', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Drama',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
