# Generated by Django 5.1.7 on 2025-05-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekomendasi', '0006_drakor_delete_drama_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='drakor',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='poster_drakor/'),
        ),
        migrations.AlterField(
            model_name='drakor',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drakor',
            name='tahun',
            field=models.IntegerField(),
        ),
    ]
